### ISSUE TITLE
New Kinvey SDK

### ISSUE THREAD

**Issue by alexbainbridge** [aaronksaunders/kinvey-starter-ionic2#1]
Hi Aaron
Firstly thanks for these sample files - very helpful! 

This Ionic 2 starter relies on the REST API from Kinvey - however the Rest API does not support all the offline syncing that their (new) Angular 2 SDK supports

https://github.com/Kinvey/javascript-sdk-core
https://github.com/Kinvey/angular2-sdk

Additionally, Ionic 2 has moved to Typescript only, and Kinvey's Angular 2 library is written for JS. There is no typings file. 

if you had any time, I would love to see a fresh Ionic 2 / Kinvey starter - in Typescript - using the new Angular 2 SDK !

**Comment by aaronksaunders** [comment]
it has been a while, but I am back to investigating this... it looks like Kinvey will only really support paid clients with issues from their support team, which makes sense.

I am working on cleaning this up to work the best it can with the rest API and then circle back to work with the angular2 functionality.

**Comment by alexbainbridge** [comment]
Hi Aaron

Thanks! Currently using the Kinvey HTML5 library.......  as per this comment https://github.com/Kinvey/angular2-sdk/issues/2#issuecomment-269976420 

Kind of works! Was coming back to test the new Angular 2 functionality when Ionic 2 moves to Typescript 2.1 which apparently has better support for untyped imports.... (as the Angular 2 library from Kinvey IS working on a plain Angular 2 JS APP, but now Ionic only supports Typescript!)

**Comment by alexbainbridge** [comment]
Guess you can close this now Aaron, thanks!
